version: '3'

services:
  orders-db:
    container_name: orders_database
    image: postgres:16.2
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports: 
      - ${PGPORT}:5432
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${PGDB}
      
